mode: deployment

service:
  type: NodePort

ports:
  jaeger-compact:
    nodePort: 6831
  jaeger-thrift:
    nodePort: 14268
  jaeger-grpc:
    nodePort: 14250
  zipkin:
    nodePort: 9411
  otlp:
    nodePort: 4317
  otlp-http:
    nodePort: 4318
